const tutorsArray = [
    {
      id: "1",
      name: "John Doe",
      subject: "Math, Science",
      location: "New York, NY",
      bio: "Experienced Math tutor with 5+ years of teaching algebra and calculus. Passionate about helping students improve grammar, writing, and literature analysis.",
      averageRating: 4.8,
      yearsOfExperience: '5+',
      mobile: '0552531004',
      email: 'johndoe@gmail.com',
      hourlyRate: 'GHS 40 per hour',
      institutionAttended: 'University of Ghana',
      modeOfPayment: 'Cash, Cheque, Mobile Money',
      teachingPreference: 'In-person',
      teachingMethodology: 'I use interactive lessons, real-life examples, and practice questions to ensure students understand concepts deeply.'
    },
    {
      id: "2",
      name: "Jane Smith",
      subject: "English",
      location: "Los Angeles, CA",
      bio: "Passionate about helping students improve grammar, writing, and literature analysis.",
      averageRating: 4.7,
    },
    {
      id: "3",
      name: "Michael Johnson",
      subject: "Physics",
      location: "Chicago, IL",
      bio: "Physics teacher with a PhD in Quantum Mechanics. I make physics fun and easy!",
      averageRating: 4.9,
    },
    {
      id: "4",
      name: "Emily Davis",
      subject: "Chemistry",
      location: "Houston, TX",
      bio: "Helping students understand chemistry through real-life examples and experiments.",
      averageRating: 4.6,
    },
    {
      id: "5",
      name: "Daniel Brown",
      subject: "Biology",
      location: "San Francisco, CA",
      bio: "Biology tutor with a specialization in human anatomy and genetics.",
      averageRating: 4.7,
    },
    {
      id: "6",
      name: "Sophia Wilson",
      subject: "Computer Science",
      location: "Seattle, WA",
      bio: "Software engineer turned educator, teaching Python, JavaScript, and AI concepts.",
      averageRating: 4.9,
    },
    {
      id: "7",
      name: "James Anderson",
      subject: "History",
      location: "Boston, MA",
      bio: "Passionate about making history exciting and relatable for students.",
      averageRating: 4.5,
    },
    {
      id: "8",
      name: "Olivia Martinez",
      subject: "French",
      location: "Miami, FL",
      bio: "Native French speaker with 8+ years of experience teaching students of all levels.",
      averageRating: 4.8,
    },
    {
      id: "9",
      name: "William Taylor",
      subject: "Economics",
      location: "Dallas, TX",
      bio: "Helping students understand micro and macroeconomics with real-world applications.",
      averageRating: 4.6,
    },
    {
      id: "10",
      name: "Emma Thomas",
      subject: "Music",
      location: "Atlanta, GA",
      bio: "Professional pianist and music instructor specializing in classical and jazz.",
      averageRating: 4.7,
    },
  ];
  
  export default tutorsArray;
  